// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Header$ReactTemplate = require("./Header.bs.js");
var MainContent$ReactTemplate = require("./MainContent.bs.js");

var component = ReasonReact.reducerComponent("App");

function initialPage() {
  var match = ReasonReact.Router[/* dangerouslyGetInitialUrl */3](/* () */0)[/* hash */1];
  switch (match) {
    case "home" : 
        return /* Home */0;
    case "newPost" : 
        return /* NewPost */1;
    case "settings" : 
        return /* Settings */2;
    case "signUp" : 
        return /* SignUp */3;
    default:
      return /* Unknown */4;
  }
}

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return /* array */[
              ReasonReact.element(/* None */0, /* None */0, Header$ReactTemplate.make(self[/* state */2][/* currentPage */0], /* array */[])),
              ReasonReact.element(/* None */0, /* None */0, MainContent$ReactTemplate.make(self[/* state */2][/* currentPage */0], /* array */[]))
            ];
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* currentPage */initialPage(/* () */0)];
    });
  newrecord[/* reducer */12] = (function (action, _) {
      return /* Update */Block.__(0, [/* record */[/* currentPage */action[0]]]);
    });
  newrecord[/* subscriptions */13] = (function (self) {
      return /* :: */[
              /* Sub */[
                (function () {
                    return ReasonReact.Router[/* watchUrl */1]((function (url) {
                                  var match = url[/* hash */1];
                                  switch (match) {
                                    case "home" : 
                                        return Curry._1(self[/* send */4], /* PathChanged */[/* Home */0]);
                                    case "newPost" : 
                                        return Curry._1(self[/* send */4], /* PathChanged */[/* NewPost */1]);
                                    case "settings" : 
                                        return Curry._1(self[/* send */4], /* PathChanged */[/* Settings */2]);
                                    case "signUp" : 
                                        return Curry._1(self[/* send */4], /* PathChanged */[/* SignUp */3]);
                                    default:
                                      return Curry._1(self[/* send */4], /* PathChanged */[/* Unknown */4]);
                                  }
                                }));
                  }),
                ReasonReact.Router[/* unwatchUrl */2]
              ],
              /* [] */0
            ];
    });
  return newrecord;
}

exports.component = component;
exports.initialPage = initialPage;
exports.make = make;
/* component Not a pure module */
