// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Header");

function text(prim) {
  return prim;
}

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("nav", {
                  className: "navbar navbar-light"
                }, React.createElement("div", {
                      className: "container"
                    }, React.createElement("a", {
                          className: "navbar-brand",
                          href: "index.html"
                        }, "conduit"), React.createElement("ul", {
                          className: "nav navbar-nav pull-xs-right"
                        }, React.createElement("li", {
                              className: "nav-item"
                            }, React.createElement("a", {
                                  className: "nav-link active",
                                  href: ""
                                }, "Home")), React.createElement("li", {
                              className: "nav-item"
                            }, React.createElement("a", {
                                  className: "nav-link",
                                  href: ""
                                }, React.createElement("i", {
                                      className: "ion-compose"
                                    }), "New post")), React.createElement("li", {
                              className: "nav-item"
                            }, React.createElement("a", {
                                  className: "nav-link",
                                  href: ""
                                }, React.createElement("i", {
                                      className: "ion-gear-a"
                                    }), "Settings")), React.createElement("li", {
                              className: "nav-item"
                            }, React.createElement("a", {
                                  className: "nav-link",
                                  href: ""
                                }, "Sign up")))));
    });
  return newrecord;
}

exports.component = component;
exports.text = text;
exports.make = make;
/* component Not a pure module */
