// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Header");

function text(prim) {
  return prim;
}

function navLinkClassList(page, linkToPage) {
  return "nav-link " + (
          Caml_obj.caml_equal(page, linkToPage) ? "active" : ""
        );
}

function make(currentPage, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("nav", {
                  className: "navbar navbar-light"
                }, React.createElement("div", {
                      className: "container"
                    }, React.createElement("a", {
                          className: "navbar-brand",
                          href: "index.html"
                        }, "conduit"), React.createElement("ul", {
                          className: "nav navbar-nav pull-xs-right"
                        }, React.createElement("li", {
                              className: "nav-item"
                            }, React.createElement("a", {
                                  className: navLinkClassList(currentPage, /* Home */0),
                                  href: "#home"
                                }, "Home")), React.createElement("li", {
                              className: "nav-item"
                            }, React.createElement("a", {
                                  className: navLinkClassList(currentPage, /* NewPost */1),
                                  href: "#newPost"
                                }, React.createElement("i", {
                                      className: "ion-compose"
                                    }), "New post")), React.createElement("li", {
                              className: "nav-item"
                            }, React.createElement("a", {
                                  className: navLinkClassList(currentPage, /* Settings */2),
                                  href: "#settings"
                                }, React.createElement("i", {
                                      className: "ion-gear-a"
                                    }), "Settings")), React.createElement("li", {
                              className: "nav-item"
                            }, React.createElement("a", {
                                  className: navLinkClassList(currentPage, /* SignUp */3),
                                  href: "#signUp"
                                }, "Sign up")))));
    });
  return newrecord;
}

exports.component = component;
exports.text = text;
exports.navLinkClassList = navLinkClassList;
exports.make = make;
/* component Not a pure module */
